compiler/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

app_name = 'compiler'
urlpatterns = [
	path('', lambda request: redirect('/start/'), name='root'),
	path('start/', views.start, name='start'),
	path('register/', views.register, name='register'),
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('main/', views.MainView, name='main'),
	path('main/file/<int:file_id>/', views.ShowingFileView, name='showingFile'),
	path('main/file/<str:file_id>/compiled/<str:standard>/<str:optimization>/<str:processor>/<str:dependent>/', views.CompiledFileView, name='compiledFile'),
	path('main/compiled/download/', views.DownloadCompiledView, name='downloadCompiled'),
	path('main/newFolder/', views.NewFolderView, name='newFolder'),
	path('main/newFile/', views.NewFileView, name='newFile'),
	path('main/deleteFolder/', views.DeleteFolderView, name='deleteFolder'),
	path('main/deleteFile/', views.DeleteFileView, name='deleteFile'),
	path('main/newSection/', views.NewSectionView, name='newSection'),
]

mysite/compiler/urls.py
from django.urls import path
from . import views

app_name = 'compiler'
urlpatterns = [
	path('start/', views.start, name='start'),
	path('register/', views.register, name='register'),
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('main/', views.MainView, name='main'),
	path('main/file/<int:file_id>/', views.ShowingFileView, name='showingFile'),
	path('main/file/<str:file_id>/compiled/<str:standard>/<str:optimization>/<str:processor>/<str:dependent>/', views.CompiledFileView, name='compiledFile'),
	path('main/compiled/download/', views.DownloadCompiledView, name='downloadCompiled'),
	path('main/newFolder/', views.NewFolderView, name='newFolder'),
	path('main/newFile/', views.NewFileView, name='newFile'),
	path('main/deleteFolder/', views.DeleteFolderView, name='deleteFolder'),
	path('main/deleteFile/', views.DeleteFileView, name='deleteFile'),
	path('main/newSection/', views.NewSectionView, name='newFile'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('compiler.urls')),
]

compiler/models.py
from django.db import models
from django.contrib.auth.models import User

class Folder(models.Model):
	parent = models.ForeignKey('Folder', on_delete=models.CASCADE, null=True, blank=True)
	name = models.TextField()
	description = models.TextField(null=True, blank=True)
	creationDate = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE, default = None, null=True, blank=True)
	isAvailable = models.BooleanField(default = True, null=True, blank=True)
	availableChangeDate = models.DateTimeField(null=True, blank=True)
	valueChangeDate = models.DateTimeField(auto_now=True, null=True, blank=True)
	
	def getFolders(self):
		return Folder.objects.filter(parent=self, owner=self.owner, isAvailable=True)
	
	def getFiles(self):
		return File.objects.filter(folder=self, owner=self.owner, isAvailable=True)

class File(models.Model):
	folder = models.ForeignKey('Folder', on_delete=models.CASCADE, null=True, blank=True)
	name = models.TextField()
	upload = models.FileField()
	description = models.TextField(null=True, blank=True)
	creationDate = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE, default = None, null=True, blank=True)
	isAvailable = models.BooleanField(default = True, null=True, blank=True)
	availableChangeDate = models.DateTimeField(null=True, blank=True)
	valueChangeDate = models.DateTimeField(auto_now=True, null=True, blank=True)

class FileToDelete(models.Model):
	file = models.ForeignKey('File', on_delete=models.CASCADE, null=True, blank=True)

SECTION_TYPE = (
	('pro', 'Procedura'),
	('com', 'Komentarz'),
	('dir', 'Dyrektywa'),
	('dec', 'Deklaracja'),
	('inl', 'Wstawka assemblerowa'),
)

SECTION_STATUS = (
	('ok', 'Kompiluje się bez ostrzeżeń'),
	('war', 'Kompiluje się z ostrzeżeniami'),
	('fail', 'Nie kompiluje się'),
)

class Section(models.Model):
	file = models.ForeignKey('File', on_delete=models.CASCADE, default=None, null=True, blank=True)
	content = models.TextField(null=True, blank=True)
	parent = models.ForeignKey('Section', on_delete=models.CASCADE, default=None, null=True, blank=True)
	name = models.TextField(null=True, blank=True)
	description = models.TextField(null=True, blank=True)
	creationDate = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE, default = None, null=True, blank=True)
	beginning = models.IntegerField(null=True, blank=True)
	ending = models.IntegerField(null=True, blank=True)
	sectionType = models.TextField(choices=SECTION_TYPE, null=True, blank=True)
	sectionStatus = models.TextField(choices=SECTION_STATUS, null=True, blank=True)

compiler/forms.py
from django import forms

from compiler.models import *

class FolderForm(forms.ModelForm):
	class Meta:
		model = Folder
		fields = [
			"parent",
			"name",
			"description",
		]

class DeleteFolderForm(forms.ModelForm):
	class Meta:
		model = Folder
		fields = [
			"parent",
		]

class FileForm(forms.ModelForm):
	class Meta:
		model = File
		fields = [
			"upload",
			"folder",
			"name",
			"description",
		]

class DeleteFileForm(forms.ModelForm):
	class Meta:
		model = FileToDelete
		fields = [
			"file",
		]

class SectionForm(forms.ModelForm):
	class Meta:
		model = Section
		fields = [
			"file",
			"name",
			"description",
			"beginning",
			"ending",
		]

compiler/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.utils import timezone
from django.http import  FileResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
import subprocess
import os, io, re

def start(request):
	return render(request, 'compiler/start.html')

def register(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('compiler:login')
	else:
		form = UserCreationForm()
	return render(request, 'compiler/register.html', {'form': form})

def user_login(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('compiler:main')
		else:
			error_message = "Invalid username or password."
	else:
		error_message = None
	return render(request, 'compiler/login.html', {'error_message': error_message})

@login_required
def user_logout(request):
    logout(request)
    return redirect('compiler:start')

@login_required
def MainView(request):
	context = {
		'folders'      : Folder.objects.filter(parent__isnull = True, isAvailable = True, owner=request.user),
		'files'        : File.objects.filter(folder__isnull = True, isAvailable = True, owner=request.user),
	}
	return render(request, 'compiler/index.html', context)

@login_required
def ShowingFileView(request, file_id):
	file = get_object_or_404(File, id = file_id)
	
	request.session['file_name'] = None
	request.session['asm_path'] = None
	request.session['asm_to_show'] = None
	request.session['err'] = None
	
	return render(request, 'compiler/showFile.html', {'file_to_show' : file.upload.open('r').read()})

@login_required
def CompiledFileView(request, file_id, standard, optimization, processor, dependent):
	if file_id == "null":
		return render(request, 'compiler/noFileSelected.html')
	file_id = int(file_id)
	
	file = get_object_or_404(File, id = file_id)
	file_name = os.path.basename(file.upload.name)
	
	command = ['sdcc', '-S']
	
	if standard != "null":
		standard = f'--std-{standard}'
		command.append(standard)
	
	if optimization != "null":
		optimization = f'--{optimization}'
		command.append(optimization)
	
	if processor != "null":
		processor = f'-m{processor}'
		command.append(processor)
	
	if dependent != "null":
		if dependent in ["small", "medium", "large"]:
			dependent = f'--model-{dependent}'
		else:
			dependent = f'--asm={dependent}'
		command.append(dependent)
	
	command.append(file_name)
	
	result = subprocess.run(command, capture_output=True, text=True)
	err = result.stderr
	asm_path = None
	compiled = None
	sections = None
	
	if not err:
		asm_path = os.path.join(os.getcwd(), file_name.rsplit('.', 1)[0] + '.asm')
		with open(asm_path, 'r') as fasm:
			compiled = fasm.read()
		
		sections = re.split(';--+', compiled)
	
	request.session['file_name'] = file.name
	request.session['asm_path'] = asm_path
	request.session['err'] = err
	request.session['asm_to_show'] = compiled
	
	return render(request, 'compiler/showCompiled.html', {'err' : err, 'sections' : sections})

@login_required
def DownloadCompiledView(request):
	asm_path = request.session['asm_path']
	content = request.session['asm_to_show']
	filename = os.path.splitext(request.session['file_name'])[0] + '.asm'
	
	file_obj = io.BytesIO(content.encode('utf-8'))
	response = FileResponse(file_obj)
	response['Content-Disposition'] = 'attachment; filename="' + filename + '"'
	
	return response

@login_required
def NewFolderView(request):
	context = {
		'current_date' : timezone.now().strftime("%Y-%m-%d %H:%M"),
		'folders'      : Folder.objects.filter(isAvailable = True, owner=request.user),
	}
	
	if request.method != "POST":
		form = FolderForm()
		context['form'] = form
		return render(request, 'compiler/newFolder.html', context)
	
	form = FolderForm(request.POST)
	
	if form.is_valid():
		folder = form.save(commit=False)
		folder.owner = request.user
		folder.save()
		return redirect('compiler:main')
	
	form = FolderForm()
	context['form'] = form
	return render(request, 'compiler/newFolder.html', context)

@login_required
def NewFileView(request):
	context = {
		'folders'      : Folder.objects.filter(isAvailable = True, owner=request.user),
	}
	
	if request.method != "POST":
		form = FileForm()
		context['form'] = form
		return render(request, 'compiler/newFile.html', context)
	
	form = FileForm(request.POST, request.FILES)
	
	if form.is_valid():
		file = form.save(commit=False)
		file.owner = request.user
		file.save()
		
		text = form.cleaned_data['upload'].open('r').read().decode('utf-8')
		
		asm = re.findall('asm.*ednasm', text, re.DOTALL)
		dyr = re.findall('#.*\n', text)
		com = re.findall('\/\/.*\n', text) + re.findall('\/\*.*\*\/', text, re.DOTALL)
		dec = re.findall('.*=.*\n', text)
		pro = re.findall('\w*\(\)\s*{.*}', text, re.DOTALL)
		
		for x in asm:
			section = Section()
			tmp = text.index(x)
			section.beginning = text[:tmp].count('\n') + 1
			section.ending = section.beginning + x.count('\n')
			section.sectionType = 'inl'
			section.content = x
			section.file = File.objects.all().latest('id')
			section.save()
		
		for x in dyr:
			section = Section()
			tmp = text.index(x)
			section.beginning = text[:tmp].count('\n') + 1
			section.ending = section.beginning + x.count('\n')
			section.sectionType = 'dir'
			section.content = x
			section.file = File.objects.all().latest('id')
			section.save()
		
		for x in com:
			section = Section()
			tmp = text.index(x)
			section.beginning = text[:tmp].count('\n') + 1
			section.ending = section.beginning + x.count('\n')
			section.sectionType = 'com'
			section.content = x
			section.file = File.objects.all().latest('id')
			section.save()
		
		for x in dec:
			section = Section()
			tmp = text.index(x)
			section.beginning = text[:tmp].count('\n') + 1
			section.ending = section.beginning + x.count('\n')
			section.sectionType = 'dec'
			section.content = x
			section.file = File.objects.all().latest('id')
			section.save()
		
		for x in pro:
			section = Section()
			tmp = text.index(x)
			section.beginning = text[:tmp].count('\n') + 1
			section.ending = section.beginning + x.count('\n')
			section.sectionType = 'pro'
			section.content = x
			section.file = File.objects.all().latest('id')
			section.save()
		
		return redirect('compiler:main')
	
	form = FileForm()
	context['form'] = form
	return render(request, 'compiler/newFile.html', context)

@login_required
def DeleteFolderView(request):
	context = {
		'folders' : Folder.objects.filter(isAvailable = True),
	}
	
	def deleteRecursive(folder):
		children = folder.getFolders()
		for child in children:
			deleteRecursive(child)
		Folder.objects.filter(id = folder.id).update(isAvailable = False)
		File.objects.filter(folder = folder).update(isAvailable = False)
	
	if request.method != "POST":
		form = DeleteFolderForm()
		context['form'] = form
		return render(request, 'compiler/deleteFolder.html', context)
	
	form = DeleteFolderForm(request.POST)
	
	if form.is_valid():
		deleteRecursive(form.cleaned_data['parent'])
		return redirect('compiler:main')
	
	form = DeleteFolderForm()
	context['form'] = form
	return render(request, 'compiler/deleteFolder.html', context)

@login_required
def DeleteFileView(request):
	context = {
		'files' : File.objects.filter(isAvailable = True),
	}
	
	if request.method != "POST":
		form = DeleteFileForm()
		context['form'] = form
		return render(request, 'compiler/deleteFile.html', context)
	
	form = DeleteFileForm(request.POST)
	
	if form.is_valid():
		file = form.cleaned_data['file']
		File.objects.filter(id = file.id).update(isAvailable = False)
		return redirect('compiler:main')
	
	form = DeleteFileForm()
	context['form'] = form
	return render(request, 'compiler/deleteFile.html', context)

@login_required
def NewSectionView(request):
	context = {
		'files' : File.objects.filter(isAvailable = True, owner=request.user),
	}
	
	if request.method != "POST":
		form = SectionForm()
		context['form'] = form
		return render(request, 'compiler/newSection.html', context)
	
	form = SectionForm(request.POST, request.FILES)
	
	if form.is_valid():
		section = form.save(commit=False)
		section.owner = request.user
		section.save()
		
		return redirect('compiler:main')
	
	form = SectionForm()
	context['form'] = form
	return render(request, 'compiler/newSection.html', context)

compiler/templates/compiler/deleteFile.html
<h1>Usuwanie pliku</h1>

<form method="POST">
	{% csrf_token %}
	<label for="file">Wybierz folder</label>
	<select id="file" name = "file">
	{% for file in files %}
		<option value = "{{ file.id }}">{{ file.name }}</option>
	{% endfor %}
	</select>
	
	<br>
	<br>

	<input type="submit" value="Usuń plik">
</form>

compiler/templates/compiler/deleteFolder.html
<h1>Usuwanie folderu</h1>

<form method="POST">
	{% csrf_token %}
	<label for="parent">Wybierz folder</label>
	<select id="parent" name = "parent">
	{% for folder in folders %}
		<option value = "{{ folder.id }}">{{ folder.name }}</option>
	{% endfor %}
	</select>
	
	<br>
	<br>

	<input type="submit" value="Usuń folder">
</form>

compiler/templates/compiler/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="utf-8">
  <title>Projekt AWWW</title>
  <link rel="stylesheet" href="{% static 'compiler/style.css'%}">
</head>

<body>
<div class="container">
  <div class="header">
    <div>
      <button onclick="location.href='/main/newFolder/'" class="menu-button">Nowy folder</button>
      <button onclick="location.href='/main/newFile/'" class="menu-button">Nowy plik</button>
      <button onclick="location.href='/main/deleteFolder/'" class="menu-button">Usuń folder</button>
      <button onclick="location.href='/main/deleteFile/'" class="menu-button">Usuń plik</button>
      <button onclick="location.href='/main/newSection/'" class="menu-button">Nowa sekcja</button>
      <button onclick="handleCompilation()" class="menu-button">Kompilacja</button>
      <button onclick="downloadCompiledFile()" class="menu-button">Pobierz</button>
    </div>
    <div style="text-align: right;">
      {% if user.is_authenticated %}
        Witaj {{ user.username }}
        <button onclick="location.href='/logout'" class="menu-button">Wyloguj</button>
      {% else %}
        <button onclick="location.href='/login'" class="menu-button">Zaloguj</button>
      {% endif %}
    </div>
  </div>
  <div class="sidebar">
    <h3>Wybór pliku</h3>
    {% include 'compiler/printTree.html' %}
  </div>
  <div class="text" id="file-content">
    <h3>Tekst Programu</h3>
  </div>
  <div class="code" id="code">
    <h3>Fragment kodu</h3>
  </div>
  <div class="buttons">
    <button id="standard" class="trapezoid-button" onClick="ShowTab('standard')">Standard</button>
    <button id="optimizations" class="trapezoid-button" onClick="ShowTab('optimizations')">Optymalizacje</button>
    <button id="processor" class="trapezoid-button" onClick="ShowTab('processor')">Procesor</button>
    <button id="dependent" class="trapezoid-button" onClick="ShowTab('dependent')">Zależne</button>
  </div>
  <div class="data" id="data-div">
    <h3>Wybierz opcje, klikając powyższe przyciski.</h3>
  </div>
</div>
<script src="{% static 'compiler/script.js' %}"></script>
</body>
</html>

compiler/templates/compiler/login.html
<h2>Login</h2>
{% if error_message %}
<p>{{ error_message }}</p>
{% endif %}
<form method="post">
  {% csrf_token %}
  <label for="username">Username:</label>
  <input type="text" id="username" name="username"><br>
  <label for="password">Password:</label>
  <input type="password" id="password" name="password"><br>
  <button type="submit">Login</button>
</form>

compiler/templates/compiler/newFile.html
<h1>Tworzenie nowego pliku</h1>

<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	
	<label for="folder">Folder</label>
	<select id="folder" name = "folder">
		<option></option>
	{% for folder in folders %}
		<option value = "{{ folder.id }}">{{ folder.name }}</option>
	{% endfor %}
	</select>

	<br>
	<br>

	<label for = "name">Nazwa pliku</label>
	<input type = "text" id = "name" name = "name" required>

	<br>
	<br>
	
	<label for = "upload">Wybierz plik</label>
	<input type = "file" id = "upload" name = "upload" required>

	<br>
	<br>

	<label for = "description">Opis (opcjonalnie)</label>
	<textarea id = "description" name = "description" rows = "6" cols = "30"></textarea>
	
	<br>
	<br>
	
	<input type="submit" value="Stwórz plik">
</form>

compiler/templates/compiler/newFolder.html
<h1>Tworzenie nowego folderu</h1>

<form method="POST">
	{% csrf_token %}
	<label for="parent">Folder nadrzędny</label>
	<select id="parent" name = "parent">
		<option></option>
	{% for folder in folders %}
		<option value = "{{ folder.id }}">{{ folder.name }}</option>
	{% endfor %}
	</select>

	<br>
	<br>

	<label for = "name">Nazwa folderu</label>
	<input type = "text" id = "name" name = "name" required>

	<br>
	<br>

	<label for = "description">Opis (opcjonalnie)</label>
	<textarea id = "description" name = "description" rows = "6" cols = "30"></textarea>
	
	<br>
	<br>
	
	<input type="submit" value="Stwórz folder">
</form>

compiler/templates/compiler/newSection.html
<h1>Tworzenie nowej sekcji</h1>

<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	
	<label for="file">Plik</label>
	<select id="file" name = "file" required>
		<option></option>
	{% for file in files %}
		<option value = "{{ file.id }}">{{ file.name }}</option>
	{% endfor %}
	</select>

	<br>
	<br>

	<label for = "name">Nazwa sekcji</label>
	<input type = "text" id = "name" name = "name" required>

	<br>
	<br>

	<label for = "description">Opis (opcjonalnie)</label>
	<textarea id = "description" name = "description" rows = "6" cols = "30"></textarea>
	
	<br>
	<br>

	<label for = "beginning">Początek sekcji</label>
	<input type = "number" id = "beginning" name = "beginning" required>
	
	<br>
	<br>
	
	<label for = "ending">Koniec sekcji</label>
	<input type = "number" id = "ending" name = "ending" required>
	
	<br>
	<br>
	
	<input type="submit" value="Stwórz sekcję">
</form>

compiler/templates/compiler/noFileSelected.html
<h3>Fragment kodu</h3>
<pre class="odd">Nie wybrano pliku.</pre>

compiler/templates/compiler/printTree.html
{% load static %}
{% for file in files %}
  <ul>
    <a class="file" onclick="handleFileClick('{{ file.id }}');">
      <img src="{% static 'compiler/images/file.png' %}" height="15px"> {{ file.name }}
    </a>
  </ul>
{% endfor %}

{% for folder in folders %}
  <ul>
    <a>
      <img src="{% static 'compiler/images/folder.png' %}" height="15px"> {{ folder.name }}
    </a>
    {% include 'compiler/printTree.html' with files=folder.getFiles folders=folder.getFolders %}
  </ul>
{% endfor %}

compiler/templates/compiler/register.html
<h2>Register</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Register</button>
</form>

compiler/templates/compiler/showCompiled.html
<h3>Fragment kodu</h3>

{% if err %}
    <pre class="odd">{{ err }}</pre>
    <br>
{% endif %}

{% if sections %}
    {% for section in sections %}
        {% if forloop.counter == 1 %}
            <div class="section-container">
                <pre class="odd" onmouseover="highlight(this)">{{ section }}</pre>
            </div>
        {% else %}
            <div class="section-container">
                <button onclick="toggleSection({{ forloop.counter }})" class="toggle-btn">&gt;</button>
                <pre class="{% cycle 'even' 'odd' %} expand-width" id="section{{ forloop.counter }}" onmouseover="highlight(this)">{{ section }}</pre>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

compiler/templates/compiler/showFile.html
<h3>Tekst Programu</h3>
<pre class="odd">{{ file_to_show }}</pre>

compiler/templates/compiler/start.html
<!DOCTYPE html>
<html>
<body>
    <p>Wybierz opcję:</p>
    <a href="{% url 'compiler:register' %}"><button>Rejestracja</button></a>
    <a href="{% url 'compiler:login' %}"><button>Logowanie</button></a>
</body>
</html>